training: 
  environment:
    env: cassie-v0
    clip_actions: true
    normalize_actions: true
    disable_env_checking: true
    env_config: 
      # The constants are defined here
      steps_per_cycle: 20
      r : 0.6

      kappa: 20
      x_cmd_vel: 2.5
      y_cmd_vel: 0
      z_cmd_vel: 0
      terminate_when_unhealthy: true
      max_simulation_steps: 400
      pelvis_height: [0.6,1.3]
      feet_distance_x: 0.6
      feet_distance_y: 0.3
      feet_distance_z: 0.3
      feet_pelvis_height: 0.3
      max_roll: 0.3
      max_pitch: 1.0
      max_yaw: 1.0
      feet_height: 0.12
      model: cassie
      frame_skip: 20
      render_mode: rgb_array
      reset_noise_scale: 0.01
      bias: 1.0
      r_biped: 4.0
      r_cmd : 2.0
      r_smooth: 1.0
      r_alternate: 1.0
      r_symmetric: 0.0
    render_env: false

  rollouts: 
    num_rollout_workers: 20
    num_envs_per_worker: 1
    rollout_fragment_length: auto
    batch_mode: truncate_episodes
    observation_filter: MeanStdFilter


  debugging: 
    logger_creator: ???
    log_level: INFO
  

  training:
    gamma: 0.99
    lr: 0.001
    train_batch_size: 15000
    model:

      fcnet_hiddens: [128, 128]
      fcnet_activation: swish
      vf_share_layers: false
      free_log_std: true
    optimizer:
      type: rmsprop
    
    use_critic: true

    use_gae: true

    lambda_: 0.92

    kl_coeff: 0.2

    sgd_minibatch_size: 5000

    num_sgd_iter: 20

    shuffle_sequences: true

    vf_loss_coeff: 0.5

    entropy_coeff: 0.01

    clip_param: 0.3

    kl_target: 0.01

    vf_clip_param: 1000.0

  framework:
    framework: torch
    eager_tracing: false

  resources:
    num_gpus: 1
    num_cpus_per_worker: 1
    num_gpus_per_worker: 0


run:
  sim_fps: ???
  sim_freq: ???
  chkpt_freq: ???
  epochs: 50000
  hyper_par_iter: 1
  n_particles: 1