a_stance: 0.5
a_swing: 0.0
b_stance: 1.0
b_swing: 0.5
bias: !!python/object/apply:numpy.core.multiarray.scalar
- &id001 !!python/object/apply:numpy.dtype
  args:
  - f8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  kLwF+/tm8D8=
feet_distance_x:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    sO4k9dq5vj8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    Qhf/ujtP8j8=
feet_distance_y:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    tldm/0WqwD8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    wMHkaPau5z8=
feet_distance_z:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    kLEa3saZzL8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    DdmZwMzX2j8=
feet_height: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  N6SJsXa94z8=
feet_pelvis_height: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  jwOjGZ4+0j8=
kappa: 25
max_simulation_steps: 400
model: cassie
pelvis_height:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    00CYJWtE8D8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    OwbgBEYZ9T8=
r_alternate: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  HTKEZ9+PAUA=
r_biped: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  oKoiSAZPDUA=
r_cmd: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  a/ciaKnWBkA=
r_smooth: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  f8TGgzDQ7T8=
render_mode: rgb_array
reset_noise_scale: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  PH+ezxxRgz8=
steps_per_cycle: 25
terminate_when_unhealthy: true
x_cmd_vel: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  uhN1UYIt9z8=
y_cmd_vel: 0
z_cmd_vel: 0
