a_stance: 0.5
a_swing: 0.0
b_stance: 1.0
b_swing: 0.5
bias: !!python/object/apply:numpy.core.multiarray.scalar
- &id001 !!python/object/apply:numpy.dtype
  args:
  - f8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  tAqfm4ld8T8=
feet_distance_x:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    cIum307IsL8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    WdQgMa6p7j8=
feet_distance_y:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    IO3fxXWsiD8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    RwhJhIhT2T8=
feet_distance_z:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    yPtWPPCbqD8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    COyJyrz74T8=
feet_height: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  T86FiSRW2T8=
feet_pelvis_height: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  Bpd9nDj51D8=
kappa: 25
max_simulation_steps: 400
model: cassie
pelvis_height:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    TBkA9h+a1D8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    iAoqjp9z/T8=
r_alternate: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  3cALIS5d9j8=
r_biped: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  5ibzJH0CF0A=
r_cmd: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  yuUG/Fdu+T8=
r_smooth: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  mGX5Fbl19D8=
render_mode: rgb_array
reset_noise_scale: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  lmRbb30Bgj8=
steps_per_cycle: 25
terminate_when_unhealthy: true
x_cmd_vel: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  XNaIaS3++z8=
y_cmd_vel: 0
z_cmd_vel: 0
