a_stance: 0.5
a_swing: 0.0
b_stance: 1.0
b_swing: 0.5
bias: !!python/object/apply:numpy.core.multiarray.scalar
- &id001 !!python/object/apply:numpy.dtype
  args:
  - f8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  IkbP+UiH6z8=
feet_distance_x:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    cMpdbNiXnj8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    1qIvnZd+6T8=
feet_distance_y:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    0jc8NkQIv78=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    nkG+NEg54T8=
feet_distance_z:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    IMr3LZJMiT8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    /hMQilQZ4z8=
feet_height: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  DL7sQPmL4z8=
feet_pelvis_height: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  T7C0Cv14zz8=
kappa: 25
max_simulation_steps: 400
model: cassie
pelvis_height:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    xhx9vWhg5D8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    G+Dgl2mi9z8=
r_alternate: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  myPb5ufXAUA=
r_biped: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  sofQ48E3DkA=
r_cmd: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  4tstjxJRB0A=
r_smooth: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  hkQkcRiW7T8=
render_mode: rgb_array
reset_noise_scale: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  +bgUjY5dgj8=
steps_per_cycle: 25
terminate_when_unhealthy: true
x_cmd_vel: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  3MS6ot3v8j8=
y_cmd_vel: 0
z_cmd_vel: 0
