wandb_version: 1

steps_per_cycle:
  desc: null
  value: 25
a_swing:
  desc: null
  value: 0
b_swing:
  desc: null
  value: 0.5
a_stance:
  desc: null
  value: 0.5
b_stance:
  desc: null
  value: 1
kappa:
  desc: null
  value: 25
x_cmd_vel:
  desc: null
  value: 1.5
y_cmd_vel:
  desc: null
  value: 0
z_cmd_vel:
  desc: null
  value: 0
terminate_when_unhealthy:
  desc: null
  value: true
max_simulation_steps:
  desc: null
  value: 400
pelvis_height:
  desc: null
  value:
  - 0.6
  - 1.5
feet_distance_x:
  desc: null
  value:
  - 0.0
  - 1.0
feet_distance_y:
  desc: null
  value:
  - 0.0
  - 0.5
feet_distance_z:
  desc: null
  value:
  - 0.0
  - 0.5
feet_pelvis_height:
  desc: null
  value: 0.3
feet_height:
  desc: null
  value: 0.6
model:
  desc: null
  value: cassie
render_mode:
  desc: null
  value: rgb_array
reset_noise_scale:
  desc: null
  value: 0.01
reward_coeffs:
  desc: null
  value:
    bias: 1.0
    r_biped: 4.0
    r_cmd: 3.0
    r_smooth: 1.0
    r_alternate: 2.0
_wandb:
  desc: null
  value:
    python_version: 3.8.16
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1686235688.048026
    t:
      1:
      - 1
      - 30
      - 55
      2:
      - 1
      - 30
      - 55
      3:
      - 16
      - 23
      4: 3.8.16
      5: 0.15.4
      8:
      - 5
