a_stance: 0.5
a_swing: 0.0
b_stance: 1.0
b_swing: 0.5
bias: !!python/object/apply:numpy.core.multiarray.scalar
- &id001 !!python/object/apply:numpy.dtype
  args:
  - f8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  dEBwUqZP0j8=
feet_distance_x:
- 0
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    oOjO4W0mrb8=
feet_distance_y:
- 0
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    CY+IO3x+7z8=
feet_distance_z:
- 0
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    fD2quwhQxb8=
feet_height: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  BM0ektcBs78=
feet_pelvis_height: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  0jbFd4F95D8=
kappa: 25
max_simulation_steps: 400
model: cassie
pelvis_height:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    y6T3LCeE2z8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    9UlgyBfu+j8=
r_alternate: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  A76cxEMeDUA=
r_biped: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  0fop5J674z8=
r_cmd: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  9kd9UM9Rhz8=
r_smooth: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  vPOGxv478D8=
render_mode: rgb_array
reset_noise_scale: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  dxsrggb61j8=
steps_per_cycle: 25
terminate_when_unhealthy: true
x_cmd_vel: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  2gyimjbz9j8=
y_cmd_vel: 0
z_cmd_vel: 0
