a_stance: 0.5
a_swing: 0.0
b_stance: 1.0
b_swing: 0.5
bias: 1
feet_distance_x:
- 0.0
- 1.0
feet_distance_y:
- 0.0
- 0.5
feet_distance_z:
- 0.0
- 0.5
feet_height: 0.6
feet_pelvis_height: 0.3
kappa: 25
max_simulation_steps: 400
model: cassie
pelvis_height:
- 0.6
- 1.5
r_alternate: 2.0
r_biped: 4.0
r_cmd: 3.0
r_smooth: 1.0
render_mode: rgb_array
reset_noise_scale: 0.001
steps_per_cycle: 25
terminate_when_unhealthy: true
x_cmd_vel: 1.5
y_cmd_vel: 0
z_cmd_vel: 0
