a_stance: 0.5
a_swing: 0.0
b_stance: 1.0
b_swing: 0.5
bias: !!python/object/apply:numpy.core.multiarray.scalar
- &id001 !!python/object/apply:numpy.dtype
  args:
  - f8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  2F3HFp8U7j8=
feet_distance_x:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    WvGmJ2VI1L8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    9cmVJD//9z8=
feet_distance_y:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    aJUVNQaJur8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    dntbLdgE4z8=
feet_distance_z:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    yEsob6xtxz8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    ExzcccMz1z8=
feet_height: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  2/aBBtQP5D8=
feet_pelvis_height: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  vuzj7dXU0T8=
kappa: 25
max_simulation_steps: 400
model: cassie
pelvis_height:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    ZiVy7c/rzz8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    CO1/T8Bc/D8=
r_alternate: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  q3/63P0QAEA=
r_biped: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  9g4hQcjyDUA=
r_cmd: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  34wW8tjxBkA=
r_smooth: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  8GP7n6l18T8=
render_mode: rgb_array
reset_noise_scale: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  z4xFw84shD8=
steps_per_cycle: 25
terminate_when_unhealthy: true
x_cmd_vel: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  vhQAW1qj+T8=
y_cmd_vel: 0
z_cmd_vel: 0
