a_stance: 0.5
a_swing: 0.0
b_stance: 1.0
b_swing: 0.5
bias: !!python/object/apply:numpy.core.multiarray.scalar
- &id001 !!python/object/apply:numpy.dtype
  args:
  - f8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  JLEDQQ1+7D8=
feet_distance_x:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    9L4ZLcdJtj8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    qgIL+sYl6D8=
feet_distance_y:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    MqMKYnFmtT8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    isdRuyso2z8=
feet_distance_z:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    LOaOdL9cqb8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    rFqHNcyA2z8=
feet_height: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  4VgNGEjD3T8=
feet_pelvis_height: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  lp5qACsV0D8=
kappa: 25
max_simulation_steps: 400
model: cassie
pelvis_height:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    NM7aGyXC3D8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    ZpK//q0P9z8=
r_alternate: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  L50qaI+AAEA=
r_biped: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  A7C9I/VfDEA=
r_cmd: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  PTNA0KajBUA=
r_smooth: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  iNrTfZCn8D8=
render_mode: rgb_array
reset_noise_scale: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  YNnhYGzygz8=
steps_per_cycle: 25
terminate_when_unhealthy: true
x_cmd_vel: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  BbKvOzos8j8=
y_cmd_vel: 0
z_cmd_vel: 0
