a_stance: 0.5
a_swing: 0.0
b_stance: 1.0
b_swing: 0.5
bias: !!python/object/apply:numpy.core.multiarray.scalar
- &id001 !!python/object/apply:numpy.dtype
  args:
  - f8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  v88quNDi8T8=
feet_distance_x:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    8ChLWz6Ln78=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    sqf4bJLX7z8=
feet_distance_y:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    AKY8MzTrir8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    1P0Y+zsK4D8=
feet_distance_z:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    ELr9TB2Xvb8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    Pu8oIpQZ2j8=
feet_height: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  EJARvpOj4D8=
feet_pelvis_height: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  s2jMGx3/1j8=
kappa: 25
max_simulation_steps: 400
model: cassie
pelvis_height:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    mCGXTD+s4D8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    HJ6aeBv0+j8=
r_alternate: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  wnkMHU+i/j8=
r_biped: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  LKMFLm5yCUA=
r_cmd: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  0xM9qOquCEA=
r_smooth: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  JtztMmC28D8=
render_mode: rgb_array
reset_noise_scale: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  TCkkrCe2gD8=
steps_per_cycle: 25
terminate_when_unhealthy: true
x_cmd_vel: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  peZzBxwQ/T8=
y_cmd_vel: 0
z_cmd_vel: 0
