run:
  chkpt_freq: 30
  epochs: 1
  hyper_par_iter: 10
  sim_fps: 30
  sim_freq: 20
training:
  debugging:
    log_level: INFO
    logger_creator: ???
  environment:
    clip_actions: true
    disable_env_checking: true
    env: cassie-v0
    env_config:
      a_stance: 5.7490843502442806
      a_swing: 0
      b_stance: 1
      b_swing: 12.342268614873811
      feet_distance_x:
      - 0.0
      - 34.55810720162468
      feet_distance_y:
      - 0.0
      - 27.019510154869582
      feet_distance_z:
      - 0.0
      - 14.769436519175928
      feet_height: 6.207686210225915
      feet_pelvis_height: 11.621512617003239
      kappa: 25
      max_simulation_steps: 400
      model: cassie
      pelvis_height:
      - 7.525272011684078
      - 57.42955418061863
      render_mode: rgb_array
      reset_noise_scale: 0.1516171998502195
      reward_coeffs:
        bias: 19.529822133717317
        r_alternate: 50.75990687805029
        r_biped: 50.667007616725904
        r_cmd: 11.91308146170217
        r_smooth: 22.87922923652618
      steps_per_cycle: 25
      terminate_when_unhealthy: true
      x_cmd_vel: 29.206848541724714
      y_cmd_vel: 0
      z_cmd_vel: 0
    normalize_actions: false
    render_env: true
  framework:
    eager_tracing: false
    framework: torch
  resources:
    num_cpus_per_worker: 1
    num_gpus: 0
    num_gpus_per_worker: 0
  rollouts:
    batch_mode: truncate_episodes
    num_envs_per_worker: 1
    num_rollout_workers: 20
    observation_filter: MeanStdFilter
    rollout_fragment_length: auto
  training:
    clip_param: 0.3
    entropy_coeff: 0.01
    gamma: 0.99
    kl_coeff: 0.2
    kl_target: 0.01
    lambda_: 0.92
    lr: 0.003
    model:
      fcnet_activation: swish
      fcnet_hiddens:
      - 128
      - 128
      free_log_std: true
      vf_share_layers: false
    num_sgd_iter: 8
    optimizer:
      type: adam
    sgd_minibatch_size: 2000
    shuffle_sequences: true
    train_batch_size: 10000
    use_critic: true
    use_gae: true
    vf_clip_param: 1000.0
    vf_loss_coeff: 0.5
