a_stance: 0.5
a_swing: 0.0
b_stance: 1.0
b_swing: 0.5
bias: !!python/object/apply:numpy.core.multiarray.scalar
- &id001 !!python/object/apply:numpy.dtype
  args:
  - f8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  Hsq9Mpf98j8=
feet_distance_x:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    aG9tYc+4qb8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    qmpiGUnj8j8=
feet_distance_y:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    iNW3Y+SEvb8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    NA6LtHM/4j8=
feet_distance_z:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    AKCtfOmGVb8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    fMwWyk1P2z8=
feet_height: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  yJYsRhfy3j8=
feet_pelvis_height: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  JrT3l7Vx0D8=
kappa: 25
max_simulation_steps: 400
model: cassie
pelvis_height:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    rK6LYlDn3j8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    XENnGng5+j8=
r_alternate: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  LNOi9QQX/D8=
r_biped: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  nRglbG+TEkA=
r_cmd: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  pImjtPZjBEA=
r_smooth: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  nkvGAqOF8z8=
render_mode: rgb_array
reset_noise_scale: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  KjHvT4Tehz8=
steps_per_cycle: 25
terminate_when_unhealthy: true
x_cmd_vel: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  QHjkCvGM/T8=
y_cmd_vel: 0
z_cmd_vel: 0
