a_stance: 0.5
a_swing: 0.0
b_stance: 1.0
b_swing: 0.5
bias: !!python/object/apply:numpy.core.multiarray.scalar
- &id001 !!python/object/apply:numpy.dtype
  args:
  - f8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  vz+OZVwK8D8=
feet_distance_x:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    tgK2Nj1m3D8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    1hmq+vnH8T8=
feet_distance_y:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    qI2oYGjjuD8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    wYkJVtIZ5z8=
feet_distance_z:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    nCr3V/LPtT8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    drZEbZ/b1T8=
feet_height: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  FxX3QCoj5T8=
feet_pelvis_height: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  Hy3MOfIm1D8=
kappa: 25
max_simulation_steps: 400
model: cassie
pelvis_height:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    lDiuwAg85T8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    5uOQt3bp/j8=
r_alternate: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  tCwr8a0e/z8=
r_biped: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  XbNeXogtEEA=
r_cmd: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  OvusauxOCkA=
r_smooth: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  YpADPxkw7T8=
render_mode: rgb_array
reset_noise_scale: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  PAQfWYEfhj8=
steps_per_cycle: 25
terminate_when_unhealthy: true
x_cmd_vel: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  A8u7F3Ki+T8=
y_cmd_vel: 0
z_cmd_vel: 0
