a_stance: 0.5
a_swing: 0.0
b_stance: 1.0
b_swing: 0.5
bias: !!python/object/apply:numpy.core.multiarray.scalar
- &id001 !!python/object/apply:numpy.dtype
  args:
  - f8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  OtL+tq1o8D8=
feet_distance_x:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    GLLfa5+20z8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    Te/+Wb8B5z8=
feet_distance_y:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    mgdNmybGyj8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    Q6NzH5jF4j8=
feet_distance_z:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    +Em7I6SGrD8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    nmDl2wYR5z8=
feet_height: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  ec0RYiqX4j8=
feet_pelvis_height: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  K7rpt6Ds0T8=
kappa: 25
max_simulation_steps: 400
model: cassie
pelvis_height:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    cOMaxzdnzT8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    etGmT5Ie9j8=
r_alternate: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  Long3Ui/AEA=
r_biped: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  HDmBJQeuDkA=
r_cmd: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  RUB4KSpGCEA=
r_smooth: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  8nfD43mb7T8=
render_mode: rgb_array
reset_noise_scale: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  pAhLM8oiiD8=
steps_per_cycle: 25
terminate_when_unhealthy: true
x_cmd_vel: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  0d+iAmY89j8=
y_cmd_vel: 0
z_cmd_vel: 0
