a_stance: 0.5
a_swing: 0.0
b_stance: 1.0
b_swing: 0.5
bias: !!python/object/apply:numpy.core.multiarray.scalar
- &id001 !!python/object/apply:numpy.dtype
  args:
  - f8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  C7nK0udY7j8=
feet_distance_x:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    PkqbxKcq2j8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    5LZb4z+s4T8=
feet_distance_y:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    GLEsGaffyj8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    khhHrgOR5T8=
feet_distance_z:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    tFdrBe1muj8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    81IshvxA3j8=
feet_height: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  LAB1Bw/W4j8=
feet_pelvis_height: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  qgbXo3N91D8=
kappa: 25
max_simulation_steps: 400
model: cassie
pelvis_height:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    i+/qptGq8D8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    xCQ0lN8E9z8=
r_alternate: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  S0LPjTQK/T8=
r_biped: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  /fwqkJKsDkA=
r_cmd: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  xBbTPWLzB0A=
r_smooth: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  L3eiXOUf7z8=
render_mode: rgb_array
reset_noise_scale: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  BPx4xaByiD8=
steps_per_cycle: 25
terminate_when_unhealthy: true
x_cmd_vel: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  vHilD80J+j8=
y_cmd_vel: 0
z_cmd_vel: 0
