a_stance: 0.5
a_swing: 0.0
b_stance: 1.0
b_swing: 0.5
bias: !!python/object/apply:numpy.core.multiarray.scalar
- &id001 !!python/object/apply:numpy.dtype
  args:
  - f8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  zQEHzk/L7T8=
feet_distance_x:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    uJcZhY/JuL8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    YaY4mMas8T8=
feet_distance_y:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    pAJDaeYyy78=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    6UHDwgg14D8=
feet_distance_z:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    KFlUDppapr8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    2Kn0eiU05T8=
feet_height: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  vc+9tCYN5T8=
feet_pelvis_height: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  2WLDtUcJ1D8=
kappa: 25
max_simulation_steps: 400
model: cassie
pelvis_height:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    TU79gqKW3j8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    2jzFULg8+z8=
r_alternate: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  phij0/p1/z8=
r_biped: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  RuyRTOjhDkA=
r_cmd: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  /E+PAS+2B0A=
r_smooth: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  fj0X3OWh7j8=
render_mode: rgb_array
reset_noise_scale: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  hJUMw4mWgj8=
steps_per_cycle: 25
terminate_when_unhealthy: true
x_cmd_vel: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  ENhjczF3+D8=
y_cmd_vel: 0
z_cmd_vel: 0
