a_stance: 0.5
a_swing: 0.0
b_stance: 1.0
b_swing: 0.5
bias: !!python/object/apply:numpy.core.multiarray.scalar
- &id001 !!python/object/apply:numpy.dtype
  args:
  - f8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  ZLgklZ3J8T8=
feet_distance_x:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    /LWQcFFXvj8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    /ho/ijbJ8j8=
feet_distance_y:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    Ipw/tMcpsT8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    qLP0n1+h3j8=
feet_distance_z:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    zORYZIWnqL8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    JLj3CdF94D8=
feet_height: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  KcrbJnwE4D8=
feet_pelvis_height: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  yS9mWSLAzj8=
kappa: 25
max_simulation_steps: 400
model: cassie
pelvis_height:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    P6vGD9g72z8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    roBdQk949z8=
r_alternate: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  bmWQrImS/D8=
r_biped: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  VFW9rielEUA=
r_cmd: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  5yRUqkK6C0A=
r_smooth: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  4RjqoftS8T8=
render_mode: rgb_array
reset_noise_scale: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  8X0H/uHJhT8=
steps_per_cycle: 25
terminate_when_unhealthy: true
x_cmd_vel: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  wj0KAOLV8z8=
y_cmd_vel: 0
z_cmd_vel: 0
