a_stance: 0.5
a_swing: 0.0
b_stance: 1.0
b_swing: 0.5
bias: !!python/object/apply:numpy.core.multiarray.scalar
- &id001 !!python/object/apply:numpy.dtype
  args:
  - f8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  +kat1lHF8D8=
feet_distance_x:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    nJZZQEyw0T8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    uYzqTzHI9z8=
feet_distance_y:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    EFtT+G9rqb8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    TAY23LIw4j8=
feet_distance_z:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    rBAtZl3rvL8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    IB6YDGwN5D8=
feet_height: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  /FQdaI2Z4z8=
feet_pelvis_height: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  WJYX0tEFxz8=
kappa: 25
max_simulation_steps: 400
model: cassie
pelvis_height:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    wr+pbYMe5z8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    hhnsCV9c9D8=
r_alternate: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  gS/XdGAmB0A=
r_biped: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  0X8iEK1HEUA=
r_cmd: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  iE5XAm9jDkA=
r_smooth: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  ZfnxmMsF4D8=
render_mode: rgb_array
reset_noise_scale: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  jr+nVzc+ij8=
steps_per_cycle: 25
terminate_when_unhealthy: true
x_cmd_vel: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  OPZ1O3uP7z8=
y_cmd_vel: 0
z_cmd_vel: 0
