a_stance: 0.5
a_swing: 0.0
b_stance: 1.0
b_swing: 0.5
bias: !!python/object/apply:numpy.core.multiarray.scalar
- &id001 !!python/object/apply:numpy.dtype
  args:
  - f8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  Nds9AwuE6D8=
feet_distance_x:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    imOSonEryT8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    lAiznWly8T8=
feet_distance_y:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    aGO5H/h/sj8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    TESvT+Q13z8=
feet_distance_z:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    Ar/augJXvz8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    s3SQCANM3z8=
feet_height: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  nzfYNDjh3z8=
feet_pelvis_height: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  zqBQaI0gzz8=
kappa: 25
max_simulation_steps: 400
model: cassie
pelvis_height:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    S6jVP/173D8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    Lq8bQP3A9D8=
r_alternate: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  zqi3znR++j8=
r_biped: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  qSLlixJEDEA=
r_cmd: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  AvsU0CVKDEA=
r_smooth: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  QsHz4zGP8j8=
render_mode: rgb_array
reset_noise_scale: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  7aRZf1dUgz8=
steps_per_cycle: 25
terminate_when_unhealthy: true
x_cmd_vel: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  bi/CmVuR+z8=
y_cmd_vel: 0
z_cmd_vel: 0
