a_stance: 0.5
a_swing: 0.0
b_stance: 1.0
b_swing: 0.5
bias: !!python/object/apply:numpy.core.multiarray.scalar
- &id001 !!python/object/apply:numpy.dtype
  args:
  - f8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  wJBaetHT8T8=
feet_distance_x:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    d1JVEIIDyj8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    DsVyWC7c7T8=
feet_distance_y:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    sKc0Hu29pj8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    vt98818R4j8=
feet_distance_z:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    +A8FfoCZs78=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    6D5FAa6i4z8=
feet_height: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  FGpR0cZQ5T8=
feet_pelvis_height: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  Zk2cKNtc0z8=
kappa: 25
max_simulation_steps: 400
model: cassie
pelvis_height:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    0EZZ2Qm36T8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    4A6p9zoe+j8=
r_alternate: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  glyMFuc6/D8=
r_biped: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  T6yhSbb7EkA=
r_cmd: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  J1RiYIGDDEA=
r_smooth: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  8K5Wng568z8=
render_mode: rgb_array
reset_noise_scale: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  CD5FyN8hgj8=
steps_per_cycle: 25
terminate_when_unhealthy: true
x_cmd_vel: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  bIoJRUqN9D8=
y_cmd_vel: 0
z_cmd_vel: 0
