a_stance: 0.5
a_swing: 0.0
b_stance: 1.0
b_swing: 0.5
bias: !!python/object/apply:numpy.core.multiarray.scalar
- &id001 !!python/object/apply:numpy.dtype
  args:
  - f8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  mO5P7+KC6j8=
feet_distance_x:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    0AF/3r4Ezb8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    /Fb5F2XY6D8=
feet_distance_y:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    AHASDqJyZL8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    IdbDZxeZ4T8=
feet_distance_z:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    EGbNMrPHor8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    JC8adEDr4z8=
feet_height: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  8Kh0sM9o4j8=
feet_pelvis_height: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  4s1ChqZI0z8=
kappa: 25
max_simulation_steps: 400
model: cassie
pelvis_height:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    SJ9bKgoG2j8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    0O7rNtJ69D8=
r_alternate: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  7CskqvIa/D8=
r_biped: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  HtgqP9FLCUA=
r_cmd: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  EXoaE82rAkA=
r_smooth: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  TCUMnS4i7T8=
render_mode: rgb_array
reset_noise_scale: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  /MQZnQxDhT8=
steps_per_cycle: 25
terminate_when_unhealthy: true
x_cmd_vel: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  IGxSJZJW9D8=
y_cmd_vel: 0
z_cmd_vel: 0
