run:
  chkpt_freq: 30
  epochs: 2
  hyper_par_iter: 10
  sim_fps: 30
  sim_freq: 20
training:
  debugging:
    log_level: INFO
    logger_creator: ???
  environment:
    clip_actions: true
    disable_env_checking: true
    env: cassie-v0
    env_config:
      a_stance: 2.533281633645318
      a_swing: 0
      b_stance: 1
      b_swing: 1.2310022254013167
      feet_distance_x:
      - 0.0
      - 9.755907298933526
      feet_distance_y:
      - 0.0
      - 2.2966945449090006
      feet_distance_z:
      - 0.0
      - 3.0526141261672644
      feet_height: 2.4770640174045195
      feet_pelvis_height: 1.7598657484119768
      kappa: 25
      max_simulation_steps: 400
      model: cassie
      pelvis_height:
      - 5.082830962567837
      - 8.65014757690008
      render_mode: rgb_array
      reset_noise_scale: 0.034278912780217545
      reward_coeffs:
        bias: 7.1340573836209
        r_alternate: 6.211913580716442
        r_biped: 12.518531622311
        r_cmd: 22.431883581215107
        r_smooth: 3.7861531692876986
      steps_per_cycle: 25
      terminate_when_unhealthy: true
      x_cmd_vel: 8.813399834430282
      y_cmd_vel: 0
      z_cmd_vel: 0
    normalize_actions: false
    render_env: true
  framework:
    eager_tracing: false
    framework: torch
  resources:
    num_cpus_per_worker: 1
    num_gpus: 0
    num_gpus_per_worker: 0
  rollouts:
    batch_mode: truncate_episodes
    num_envs_per_worker: 1
    num_rollout_workers: 16
    observation_filter: MeanStdFilter
    rollout_fragment_length: auto
  training:
    clip_param: 0.3
    entropy_coeff: 0.01
    gamma: 0.99
    kl_coeff: 0.2
    kl_target: 0.01
    lambda_: 0.92
    lr: 0.003
    model:
      fcnet_activation: swish
      fcnet_hiddens:
      - 128
      - 128
      free_log_std: true
      vf_share_layers: false
    num_sgd_iter: 8
    optimizer:
      type: adam
    sgd_minibatch_size: 2000
    shuffle_sequences: true
    train_batch_size: 10000
    use_critic: true
    use_gae: true
    vf_clip_param: 1000.0
    vf_loss_coeff: 0.5
