a_stance: 0.5
a_swing: 0.0
b_stance: 1.0
b_swing: 0.5
bias: !!python/object/apply:numpy.core.multiarray.scalar
- &id001 !!python/object/apply:numpy.dtype
  args:
  - f8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  Fm+5Mt667z8=
feet_distance_x:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    VL8hmUktyr8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    mNg6hSMx8j8=
feet_distance_y:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    omTSh2/CyL8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    +IUeYtsc4T8=
feet_distance_z:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    rIH4XWHkuj8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    LioSzRf61j8=
feet_height: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  EmYdJLRv4T8=
feet_pelvis_height: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  WGr4ywGw0z8=
kappa: 25
max_simulation_steps: 400
model: cassie
pelvis_height:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    DzBDF63X3j8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    2ePBM9hG8T8=
r_alternate: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  /W/6YFTMAEA=
r_biped: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  bygmXumHEEA=
r_cmd: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  0n02GpoxB0A=
r_smooth: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  6uqH+X617z8=
render_mode: rgb_array
reset_noise_scale: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  sobLrU6+hz8=
steps_per_cycle: 25
terminate_when_unhealthy: true
x_cmd_vel: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  gKjAKfM7+D8=
y_cmd_vel: 0
z_cmd_vel: 0
