a_stance: 0.5
a_swing: 0.0
b_stance: 1.0
b_swing: 0.5
bias: !!python/object/apply:numpy.core.multiarray.scalar
- &id001 !!python/object/apply:numpy.dtype
  args:
  - f8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  KaWqiB/28T8=
feet_distance_x:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    zHQs8LgXvL8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    4rcdDtJg8D8=
feet_distance_y:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    /DmX53asqz8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    JWpqds5C4T8=
feet_distance_z:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    bFdZtsberL8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    7I/BAcws4T8=
feet_height: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  jivu3cg65T8=
feet_pelvis_height: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  gkv68ilZzz8=
kappa: 25
max_simulation_steps: 400
model: cassie
pelvis_height:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    6AtnX1MF6D8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    AlLpKNtz+D8=
r_alternate: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  W9t6j1aOAEA=
r_biped: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  O1ka5iAZE0A=
r_cmd: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  xvIUuQDxBkA=
r_smooth: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  Rrk9aC6s8D8=
render_mode: rgb_array
reset_noise_scale: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  eCMzLzOPgT8=
steps_per_cycle: 25
terminate_when_unhealthy: true
x_cmd_vel: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  gHgoQ9ID+j8=
y_cmd_vel: 0
z_cmd_vel: 0
