a_stance: 0.5
a_swing: 0.0
b_stance: 1.0
b_swing: 0.5
bias: !!python/object/apply:numpy.core.multiarray.scalar
- &id001 !!python/object/apply:numpy.dtype
  args:
  - f8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  Ddv3IteE8T8=
feet_distance_x:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    zulFEeJL0r8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    CNOyWtXu6z8=
feet_distance_y:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    KKQqIuFizT8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    3K1uNJ+91z8=
feet_distance_z:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    zoIYUsHBzD8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    mZwY9kdS0D8=
feet_height: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  ACb6FWlK4T8=
feet_pelvis_height: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  +mRc7RAM0j8=
kappa: 25
max_simulation_steps: 400
model: cassie
pelvis_height:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    mqU9m43O0D8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    pUt6ubRU8z8=
r_alternate: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  BR8NNUZ4/z8=
r_biped: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  XP1AZd4WEUA=
r_cmd: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  9DVELBTIBkA=
r_smooth: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  MfjtaCce8D8=
render_mode: rgb_array
reset_noise_scale: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  pTepjQdVgj8=
steps_per_cycle: 25
terminate_when_unhealthy: true
x_cmd_vel: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  p6kRvv3X9j8=
y_cmd_vel: 0
z_cmd_vel: 0
