training:
  environment:
    env: cassie-v0
    normalize_actions: true
    clip_actions: true  
    env_config: 
      symmetric_regulation: false
      steps_per_cycle: 25
      r: 0.6
      kappa: 20
      x_cmd_vel: 0.7
      y_cmd_vel: 0.0
      z_cmd_vel: 0
      terminate_when_unhealthy: true
      max_simulation_steps: 300
      pelvis_height: [0.5, 1.25]
      feet_distance_x: 1.0
      feet_distance_y: 0.8
      feet_distance_z: 0.5
      feet_pelvis_height: 0.25
      max_roll: 2.0
      max_pitch: 2.0
      max_yaw: 10.0
      feet_height: 0.30
      model: cassie
      frame_skip: 20
      render_mode: rgb_array
      width: 1920
      height: 1080
      reset_noise_scale: 0.05  # Reduced from 0.1 to decrease initial exploration
      force_max_norm: 30.0
      push_freq: 80  
      push_duration: 5
      bias: -0.01  # Slightly increased from -0.002 to make the reward less negative
      r_biped: 0.0
      r_cmd: 1.0  # Increased from 0.3 to encourage following the command velocity
      r_smooth: 0.0 # Increased from 0.1 to encourage smoother actions
    render_env: false

  env_runners: 
    num_env_runners: 20
    num_envs_per_env_runner: 1
    num_cpus_per_env_runner: 1
    rollout_fragment_length: auto
    batch_mode: truncate_episodes
    observation_filter: MeanStdFilter
    validate_env_runners_after_construction: true
    use_worker_filter_stats: true

  debugging: 
    logger_creator: ???
    log_level: INFO
  
  fault_tolerance:
    recreate_failed_env_runners: true
    ignore_env_runner_failures: true 
    restart_failed_sub_environments: true
    
  training:

    train_batch_size: 8192
    sgd_minibatch_size: 512
    num_sgd_iter: 16

    # clip_param: 0.3

    # gamma: 0.99
    # lambda_: 0.95

    # kl_target: 0.01
    # kl_coeff: 0.2

    grad_clip: 1.0

    model:
      fcnet_hiddens: [256, 256] 
      # fcnet_activation: elu 
      fcnet_weights_initializer: xavier_uniform_
      fcnet_bias_initializer: zeros
      # post_fcnet_activation: elu 

    # use_critic: true
    # use_gae: true

    shuffle_sequences: true

    # vf_loss_coeff: 1.0
    # entropy_coeff: 0.05


  framework:
    framework: torch
    torch_compile_worker_dynamo_backend: ipex
    torch_compile_worker_dynamo_mode: max-autotune

  resources:
    num_gpus: 1

run:
  render_every: 1200
  save_every: 3600
  epochs: 50000
  sim_fps: 60
  hyper_par_iter: 1
  n_particles: 1