training:
  environment:
    env: cassie-v0
    clip_actions: false
    normalize_actions: false
    env_config:
      # The constants are defined here
      symmetric_regulation: true
      dt_per_cycle: 1.0
      r : 0.6
      kappa: 20
      x_cmd_vel: 0.5
      y_cmd_vel: 0.0
      z_cmd_vel: 0
      terminate_when_unhealthy: true
      max_simulation_time: 10 # seconds
      pelvis_height: [0.5,1.5]
      feet_distance_x: 1.2
      feet_distance_y: 0.6
      feet_distance_z: 0.5
      feet_pelvis_height: 0.20
      max_roll: 2.0
      max_pitch: 2.0
      max_yaw: 10.0
      feet_height: 0.30
      model: cassie
      sim_fps: 60
      render_mode: rgb_array
      width: 1920
      height: 1080
      reset_noise_scale: 0.05
      force_max_norm: 0.0
      push_prob: 0.01 #  1% of the time
      push_duration: 0.1 # seconds
      bias: -0.1 # Make sure reward can be negative
      r_biped: 1.0
      r_cmd : 0.5
      r_smooth: 0.1
    render_env: false

  env_runners:
    enable_tf1_exec_eagerly: true
    num_env_runners: 20
    num_envs_per_env_runner: 1
    num_cpus_per_env_runner: 1.0
    num_gpus_per_env_runner: 0.05
    rollout_fragment_length: auto
    batch_mode: truncate_episodes
    observation_filter: MeanStdFilter


  debugging:
    logger_creator: ???
    log_level: INFO

  fault_tolerance:
    restart_failed_env_runners: true
    ignore_env_runner_failures: false
    restart_failed_sub_environments: true

  training:
    # Core training parameters
    gamma: 0.99
    grad_clip: 1.0
    train_batch_size: 16384 # Note: may need adjustment based on total env runners & learners if using train_batch_size_per_learner

    # Model configuration
    model:
      fcnet_hiddens: [256, 256]
      fcnet_activation: elu
      fcnet_weights_initializer: xavier_uniform_
      fcnet_bias_initializer: zeros
      post_fcnet_activation: elu
      free_log_std: true
      vf_share_layers: false # Explicitly setting based on PPO defaults

    # Optimizer configuration
    optimizer:
      type: adam

    # PPO specific parameters
    use_critic: true
    use_gae: true
    lambda_: 0.92
    use_kl_loss: true
    kl_coeff: 0.2
    kl_target: 0.01
    minibatch_size: 1024 # Renamed from sgd_minibatch_size
    num_epochs: 16       # Renamed from num_sgd_iter
    shuffle_batch_per_epoch: true # Renamed from shuffle_sequences
    vf_loss_coeff: 0.5
    entropy_coeff: 0.003
    clip_param: 0.3
    vf_clip_param: 10.0

  framework:
    framework: torch
    torch_compile_worker_dynamo_backend: ipex
    torch_compile_worker_dynamo_mode: max-autotune

  resources:
    num_gpus: 1



run:
  render_fps: 30
  render_every: 600 # seconds
  chkpt_freq: 2400 # seconds
  epochs: 50000000
  hyper_par_iter: 1
  n_particles: 1
