training: 
  environment:
    env: cassie-v0
    clip_actions: true
    normalize_actions: true
    env_config: 
      # The constants are defined here
      steps_per_cycle: 20
      r : 0.6
      kappa: 20
      x_cmd_vel: 0.5
      y_cmd_vel: 0.0
      z_cmd_vel: 0
      terminate_when_unhealthy: true
      max_simulation_steps: 500
      pelvis_height: [0.65,1.35]
      feet_distance_x: 1.0
      feet_distance_y: 0.6
      feet_distance_z: 0.5
      feet_pelvis_height: 0.1
      max_roll: 2.0
      max_pitch: 2.0
      max_yaw: 10.0
      feet_height: 0.30
      model: cassie
      frame_skip: 40
      render_mode: rgb_array
      width: 1920
      height: 1080
      reset_noise_scale: 0.04
      bias: 1.0
      r_biped: 0.8
      r_cmd : 1.0
      r_smooth: 0.2
    render_env: false

  env_runners: 
    num_env_runners: 20
    num_envs_per_env_runner: 1
    num_cpus_per_env_runner: 1
    num_gpus_per_env_runner: 0
    rollout_fragment_length: auto
    batch_mode: truncate_episodes
    observation_filter: MeanStdFilter


  debugging: 
    logger_creator: ???
    log_level: INFO
  
  fault_tolerance:
    recreate_failed_env_runners: true

  training:

    gamma: 0.99
    grad_clip: 40.0
    train_batch_size: 16384
    model:
      fcnet_hiddens: [256, 256]
      # fcnet_activation: elu
    optimizer:
      type: adam
        
    use_critic: true

    use_gae: true

    lambda_: 0.92

    kl_coeff: 0.2

    sgd_minibatch_size: 512

    num_sgd_iter: 16

    shuffle_sequences: true

    vf_loss_coeff: 0.5

    entropy_coeff: 0.003

    clip_param: 0.3

    kl_target: 0.01

  framework:
    framework: torch
    torch_compile_worker_dynamo_backend: ipex
    torch_compile_worker_dynamo_mode: max-autotune

  resources:
    num_gpus: 1



run:
  sim_fps: ???
  sim_freq: ???
  chkpt_freq: ???
  epochs: 50000
  hyper_par_iter: 1
  n_particles: 1
