a_stance: 0.5
a_swing: 0.0
b_stance: 1.0
b_swing: 0.5
bias: !!python/object/apply:numpy.core.multiarray.scalar
- &id001 !!python/object/apply:numpy.dtype
  args:
  - f8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  tvn4rVOb6z8=
feet_distance_x:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    iFPu3T2Jvb8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    0mTlULra7T8=
feet_distance_y:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    ALvYkfSQoz8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    5rqlhcBc3D8=
feet_distance_z:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    mHv4UPoRtz8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    R8jqYzgG0z8=
feet_height: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  Af2Pig3R3z8=
feet_pelvis_height: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  xxNqClYh1T8=
kappa: 25
max_simulation_steps: 400
model: cassie
pelvis_height:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    gtW8F4aj2D8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    tEhYEAiH9j8=
r_alternate: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  ChcSs2bm8T8=
r_biped: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  PUi7b1X8FEA=
r_cmd: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  ONiZPACUDkA=
r_smooth: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  IRx0OrXA4T8=
render_mode: rgb_array
reset_noise_scale: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  hIUKhdkAjj8=
steps_per_cycle: 25
terminate_when_unhealthy: true
x_cmd_vel: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  hPYL3Q5CAUA=
y_cmd_vel: 0
z_cmd_vel: 0
