a_stance: 0.5
a_swing: 0.0
b_stance: 1.0
b_swing: 0.5
bias: !!python/object/apply:numpy.core.multiarray.scalar
- &id001 !!python/object/apply:numpy.dtype
  args:
  - f8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  2gTh81lg1D8=
feet_distance_x:
- 0
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    kFxP+HvW1z8=
feet_distance_y:
- 0
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    cDb3U1zr6D8=
feet_distance_z:
- 0
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    yNM/YNGByj8=
feet_height: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  +Hdo9Hcwpr8=
feet_pelvis_height: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  cqM2EHF75T8=
kappa: 25
max_simulation_steps: 400
model: cassie
pelvis_height:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    7sp5qsYY4T8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    2CFJuctO+z8=
r_alternate: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  WoG9jbCbDkA=
r_biped: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  JXdJAel54T8=
r_cmd: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  ENtt0z+vgj8=
r_smooth: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  urUOc+qH7j8=
render_mode: rgb_array
reset_noise_scale: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  RBJMEeoa3j8=
steps_per_cycle: 25
terminate_when_unhealthy: true
x_cmd_vel: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  FozwRo3q+T8=
y_cmd_vel: 0
z_cmd_vel: 0
