a_stance: 0.5
a_swing: 0.0
b_stance: 1.0
b_swing: 0.5
bias: !!python/object/apply:numpy.core.multiarray.scalar
- &id001 !!python/object/apply:numpy.dtype
  args:
  - f8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  asa02RuR7T8=
feet_distance_x:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    tFRlRfZ+yD8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    6MEWq/s86D8=
feet_distance_y:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    VI34sfC8tb8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    wE25kQVb4T8=
feet_distance_z:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    oDsiR2SQjT8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    R+uX4AOH0T8=
feet_height: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  pLmyQZCD4T8=
feet_pelvis_height: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  H9vM1tbB0T8=
kappa: 25
max_simulation_steps: 400
model: cassie
pelvis_height:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    Yasa+0UA3D8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    0hsMzRiv8T8=
r_alternate: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  2ZpIxgKGAUA=
r_biped: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  wmrJUP2oEEA=
r_cmd: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  giEq3uNdCUA=
r_smooth: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  8E5UvSEm8T8=
render_mode: rgb_array
reset_noise_scale: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  VnSX0fKRgT8=
steps_per_cycle: 25
terminate_when_unhealthy: true
x_cmd_vel: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  fyUV5+eZ9z8=
y_cmd_vel: 0
z_cmd_vel: 0
