a_stance: 0.5
a_swing: 0.0
b_stance: 1.0
b_swing: 0.5
bias: !!python/object/apply:numpy.core.multiarray.scalar
- &id001 !!python/object/apply:numpy.dtype
  args:
  - f8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  fYBeAFsn8T8=
feet_distance_x:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    EK9MGaKrzL8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    ZO6/5qTV8D8=
feet_distance_y:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    XLzS3L9stb8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    tI53unSR4T8=
feet_distance_z:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    dHFJHxiCxj8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    Vnzo4J3/4D8=
feet_height: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  X2gNEXcB5D8=
feet_pelvis_height: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  95xX5Rng0z8=
kappa: 25
max_simulation_steps: 400
model: cassie
pelvis_height:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    vnnL789i7T8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    2vV64Rr4+j8=
r_alternate: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  cZRfuozgAEA=
r_biped: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  3HXocGOOEUA=
r_cmd: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  02xQxgYGCEA=
r_smooth: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  e2W7nzHp8D8=
render_mode: rgb_array
reset_noise_scale: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  hcqAMybAgT8=
steps_per_cycle: 25
terminate_when_unhealthy: true
x_cmd_vel: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  A6Itw5hK+T8=
y_cmd_vel: 0
z_cmd_vel: 0
