a_stance: 0.5
a_swing: 0.0
b_stance: 1.0
b_swing: 0.5
bias: !!python/object/apply:numpy.core.multiarray.scalar
- &id001 !!python/object/apply:numpy.dtype
  args:
  - f8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  Yjuen9cu8j8=
feet_distance_x:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    COgFZkLgzj8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    x/kKeX9a8T8=
feet_distance_y:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    VOZEPCGwoD8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    SMsFPEqe4D8=
feet_distance_z:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    JlZZvhW9uL8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    /tNv+cw84j8=
feet_height: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  ytXUYMOf4D8=
feet_pelvis_height: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  eYgPalnt1T8=
kappa: 25
max_simulation_steps: 400
model: cassie
pelvis_height:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    1dlWQktA5T8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    WERjTkrM+D8=
r_alternate: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  TTdVHYpE+z8=
r_biped: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  4IYCjHrpDUA=
r_cmd: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  boupl8paDEA=
r_smooth: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  Esn9T4EA8T8=
render_mode: rgb_array
reset_noise_scale: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  VEeJoDaWgj8=
steps_per_cycle: 25
terminate_when_unhealthy: true
x_cmd_vel: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  CtJ1ZRBo/D8=
y_cmd_vel: 0
z_cmd_vel: 0
