a_stance: 0.5
a_swing: 0.0
b_stance: 1.0
b_swing: 0.5
bias: !!python/object/apply:numpy.core.multiarray.scalar
- &id001 !!python/object/apply:numpy.dtype
  args:
  - f8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  IHaiSV758T8=
feet_distance_x:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    3L/XsaVvsL8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    tKn13faV8j8=
feet_distance_y:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    wEcACMtqnD8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    7FvAr+Fg3T8=
feet_distance_z:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    0Km2xgHfuL8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    cLQo4OB04D8=
feet_height: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  VFbX73UH3T8=
feet_pelvis_height: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  qpbPhSzR0z8=
kappa: 25
max_simulation_steps: 400
model: cassie
pelvis_height:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    jplf3i5z4T8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    6YANKwK69z8=
r_alternate: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  tLCbx+n5A0A=
r_biped: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  hcoPn6XgE0A=
r_cmd: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  ybXIDFUxA0A=
r_smooth: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  u2ZzUy7m8D8=
render_mode: rgb_array
reset_noise_scale: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  9Me2Wq4NgT8=
steps_per_cycle: 25
terminate_when_unhealthy: true
x_cmd_vel: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  AnVUnPh//T8=
y_cmd_vel: 0
z_cmd_vel: 0
