a_stance: 0.5
a_swing: 0.0
b_stance: 1.0
b_swing: 0.5
bias: !!python/object/apply:numpy.core.multiarray.scalar
- &id001 !!python/object/apply:numpy.dtype
  args:
  - f8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  LGEguN8V7j8=
feet_distance_x:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    8BqlvPgX0T8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    S3/deK8t4j8=
feet_distance_y:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    iCel5p5Swb8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    VsC3Fbmz5D8=
feet_distance_z:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    /hhxqJyNw78=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    d7eyTUJ/3T8=
feet_height: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  nGPJ1OEe4D8=
feet_pelvis_height: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  2xfMe7ID1D8=
kappa: 25
max_simulation_steps: 400
model: cassie
pelvis_height:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    O+tMnrdc3j8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    91E0XYv9+z8=
r_alternate: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  c/dSqmkZ8T8=
r_biped: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  vChqsV5zAEA=
r_cmd: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  bnEIF7kA/T8=
r_smooth: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  unYeQBUQ4D8=
render_mode: rgb_array
reset_noise_scale: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  Tic0wrLPgj8=
steps_per_cycle: 25
terminate_when_unhealthy: true
x_cmd_vel: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  jvStMxWm6T8=
y_cmd_vel: 0
z_cmd_vel: 0
