a_stance: 0.5
a_swing: 0.0
b_stance: 1.0
b_swing: 0.5
bias: !!python/object/apply:numpy.core.multiarray.scalar
- &id001 !!python/object/apply:numpy.dtype
  args:
  - f8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  /BuzLjtD8j8=
feet_distance_x:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    MKUkMEx1rz8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    Uf61PdPE8D8=
feet_distance_y:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    TBh6f4gOtb8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    ttGbBvVL3z8=
feet_distance_z:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    LC2nzsbivz8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    0l0TC5+I4D8=
feet_height: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  MlFcU2D/5D8=
feet_pelvis_height: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  yM4ARpJA0z8=
kappa: 25
max_simulation_steps: 400
model: cassie
pelvis_height:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    PwuRS2Zw2D8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    JqcZKv1y+D8=
r_alternate: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  ScDHpso+A0A=
r_biped: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  feiQaH7XEEA=
r_cmd: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  Dgo13y1xDUA=
r_smooth: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  k+DLxV978j8=
render_mode: rgb_array
reset_noise_scale: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  B4SiJaB3fz8=
steps_per_cycle: 25
terminate_when_unhealthy: true
x_cmd_vel: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  txTgwn+H9D8=
y_cmd_vel: 0
z_cmd_vel: 0
